name: Purge Camo Cache

on:
  schedule:
    # 1시간마다 자동 실행하여 캐시 정제
    - cron: '0 * * * *'
  # Actions 탭에서 'Run workflow' 버튼으로 수동 즉시 실행 가능
  workflow_dispatch:

jobs:
  purge-camo-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Purge Camo Cache
        uses: kevincobain2000/action-camo-purge@v1
